name: kibot

on: 
  - pull_request
  - push
#    paths:
#      - '**.kicad_sch'
#      - '**.kicad_pcb'

jobs:
  kibot:
    runs-on: ubuntu-latest 
    container: ghcr.io/inti-cmnb/kicad8_auto:latest
    strategy:
      matrix:
        pcb: [BOOST, BUS, CONN, LOG, LORA, POS]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    # Start of the KiBot steps
    - name: Run KiBot
      run: kibot -d ${{ matrix.pcb }} -c ${{ matrix.pcb }}/variant.kibot.yml -e "${{ matrix.pcb }}/pcb/${{ matrix.pcb }}.kicad_sch" -b "${{ matrix.pcb }}/pcb/${{ matrix.pcb }}.kicad_pcb"

    # git add, commit and push
    - uses: actions4git/add-commit-push@v1