name: Release

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: KiBot
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: KiBot
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: ArduinoCI
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ArduinoCI
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}
          if-no-files-found: error
          path: .
    
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: commit to repository
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: docs
          name: auto release
          rebase: true
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
  